version: '2.0'
services:

  config:
    container_name: config-server
    build: config
    image: ch.awae/config
    restart: always

  registry:
    container_name: registry-server
    build: registry
    image: ch.awae/registry
    restart: always
    ports:
      - 8761:8761

  gateway:
    container_name: gateway-server
    build: gateway
    ports:
      - 4000:4000
    image: ch.awae/gateway
    restart: always

  auth-service:
    container_name: auth-service
    build: auth-service
    image: ch.awae/auth-service
    restart: always

  test-service:
    container_name: elite-service
    build: elite-service
    image: ch.awae/elite-service
    restart: always

  shorten-service:
    container_name: shorten-service
    build: shorten-service
    image: ch.awae/shorten-service
    restart: always

  netcode-service:
    container_name: netcode-service
    build: netcode-service
    image: ch.awae/netcode-service
    restart: always
    
