version: '2.0'
services:

  config:
    container_name: config-server
    build: config
    image: ch.awae/config
    restart: always

  registry:
    container_name: registry-server
    build: registry
    image: ch.awae/registry
    restart: always
    ports:
      - 8761:8761

  gateway:
    container_name: gateway-server
    build: gateway
    ports:
      - 4000:4000
    image: ch.awae/gateway
    restart: always

  test-service:
    container_name: test-service
    build: test-service
    image: ch.awae/test-service
    restart: always
    